"""add material requests tables

Revision ID: f29cadf80750
Revises: add_pdm_templates
Create Date: 2026-02-26 09:42:27.958036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f29cadf80750'
down_revision: Union[str, Sequence[str], None] = 'add_pdm_templates'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pdm_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requester', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pdm_id'], ['pdm_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['material_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_values')
    op.drop_table('material_requests')
    # ### end Alembic commands ###
