"""
Constantes compartilhadas para onboarding e seed.
"""

# Roles padrão para novo tenant (6 etapas + ADMIN, SOLICITANTE, MASTER)
ONBOARDING_ROLE_DEFS = [
    {
        "name": "ADMIN",
        "role_type": "sistema",
        "permissions": {
            "can_submit_request": True,
            "can_approve": True,
            "can_reject": True,
            "can_edit_pdm": True,
            "can_view_pdm": True,
            "can_view_logs": True,
            "can_bulk_import": True,
            "can_standardize": True,
            "can_manage_roles": True,
            "can_manage_users": True,
            "can_manage_fields": True,
            "can_view_database": True,
            "can_edit_workflows": True,
            "can_view_workflows": True,
        },
    },
    {
        "name": "SOLICITANTE",
        "role_type": "operacional",
        "permissions": {
            "can_submit_request": True,
            "can_approve": False,
            "can_reject": False,
            "can_edit_pdm": False,
            "can_view_pdm": True,
            "can_view_logs": False,
            "can_bulk_import": False,
            "can_standardize": False,
            "can_manage_roles": False,
            "can_manage_users": False,
            "can_manage_fields": False,
            "can_view_database": True,
            "can_edit_workflows": False,
            "can_view_workflows": True,
        },
    },
    {
        "name": "CADASTRO",
        "role_type": "operacional",
        "permissions": {
            "can_submit_request": True,
            "can_approve": True,
            "can_reject": True,
            "can_edit_pdm": True,
            "can_view_pdm": True,
            "can_view_logs": False,
            "can_bulk_import": True,
            "can_standardize": True,
            "can_manage_roles": False,
            "can_manage_users": False,
            "can_manage_fields": True,
            "can_view_database": True,
            "can_edit_workflows": False,
            "can_view_workflows": True,
        },
    },
    {
        "name": "COMPRAS",
        "role_type": "operacional",
        "permissions": {
            "can_submit_request": False,
            "can_approve": True,
            "can_reject": True,
            "can_edit_pdm": False,
            "can_view_pdm": True,
            "can_view_logs": False,
            "can_bulk_import": False,
            "can_standardize": False,
            "can_manage_roles": False,
            "can_manage_users": False,
            "can_manage_fields": False,
            "can_view_database": True,
            "can_edit_workflows": False,
            "can_view_workflows": True,
        },
    },
    {
        "name": "MRP",
        "role_type": "operacional",
        "permissions": {
            "can_submit_request": False,
            "can_approve": True,
            "can_reject": True,
            "can_edit_pdm": False,
            "can_view_pdm": True,
            "can_view_logs": False,
            "can_bulk_import": False,
            "can_standardize": False,
            "can_manage_roles": False,
            "can_manage_users": False,
            "can_manage_fields": False,
            "can_view_database": True,
            "can_edit_workflows": False,
            "can_view_workflows": True,
        },
    },
    {
        "name": "FISCAL",
        "role_type": "operacional",
        "permissions": {
            "can_submit_request": False,
            "can_approve": True,
            "can_reject": True,
            "can_edit_pdm": False,
            "can_view_pdm": True,
            "can_view_logs": False,
            "can_bulk_import": False,
            "can_standardize": False,
            "can_manage_roles": False,
            "can_manage_users": False,
            "can_manage_fields": False,
            "can_view_database": True,
            "can_edit_workflows": False,
            "can_view_workflows": True,
        },
    },
    {
        "name": "CONTABILIDADE",
        "role_type": "operacional",
        "permissions": {
            "can_submit_request": False,
            "can_approve": True,
            "can_reject": True,
            "can_edit_pdm": False,
            "can_view_pdm": True,
            "can_view_logs": False,
            "can_bulk_import": False,
            "can_standardize": False,
            "can_manage_roles": False,
            "can_manage_users": False,
            "can_manage_fields": False,
            "can_view_database": True,
            "can_edit_workflows": False,
            "can_view_workflows": True,
        },
    },
    {
        "name": "MASTER",
        "role_type": "sistema",
        "permissions": {
            "can_submit_request": True,
            "can_approve": True,
            "can_reject": True,
            "can_edit_pdm": True,
            "can_view_pdm": True,
            "can_view_logs": True,
            "can_bulk_import": True,
            "can_standardize": True,
            "can_manage_roles": True,
            "can_manage_users": True,
            "can_manage_fields": True,
            "can_view_database": True,
            "can_edit_workflows": True,
            "can_view_workflows": True,
        },
    },
]

# Etapas do workflow padrão (6 etapas)
ONBOARDING_WORKFLOW_STEPS = [
    {"step_order": 1, "step_name": "Central de Cadastro", "role_name": "CADASTRO", "status_key": "cadastro", "order": 1},
    {"step_order": 2, "step_name": "Compras", "role_name": "COMPRAS", "status_key": "compras", "order": 2},
    {"step_order": 3, "step_name": "MRP", "role_name": "MRP", "status_key": "mrp", "order": 3},
    {"step_order": 4, "step_name": "Fiscal", "role_name": "FISCAL", "status_key": "fiscal", "order": 4},
    {"step_order": 5, "step_name": "Contabilidade", "role_name": "CONTABILIDADE", "status_key": "contabilidade", "order": 5},
    {"step_order": 6, "step_name": "Finalizado", "role_name": None, "status_key": "finalizado", "order": 6},
]

# Field dictionary padrão ERP (31 campos) — responsible_role mapeado para novo workflow
ONBOARDING_FIELD_DICT = [
    {"field_name": "descricao_basica", "field_label": "Descrição Básica", "sap_field": "MAKTX",
     "sap_view": "dados_basicos", "field_type": "text", "options": None, "responsible_role": "CADASTRO",
     "is_required": True, "display_order": 1},
    {"field_name": "grupo_mercadorias", "field_label": "Grupo de Mercadorias", "sap_field": "MATKL",
     "sap_view": "dados_basicos", "field_type": "select",
     "options": ["001 - Matéria-prima", "002 - Semimanufaturado", "003 - Produto acabado", "004 - Mercadoria para revenda"],
     "responsible_role": "CADASTRO", "is_required": True, "display_order": 2},
    {"field_name": "unidade_medida_base", "field_label": "Unidade de Medida Base", "sap_field": "MEINS",
     "sap_view": "dados_basicos", "field_type": "select",
     "options": ["UN", "KG", "L", "M", "M2", "M3", "PC", "CX"],
     "responsible_role": "CADASTRO", "is_required": True, "display_order": 3},
    {"field_name": "tipo_material", "field_label": "Tipo de Material", "sap_field": "MTART",
     "sap_view": "dados_basicos", "field_type": "select",
     "options": ["FERT - Produto acabado", "HALB - Semimanufaturado", "ROH - Matéria-prima", "HAWA - Mercadoria para revenda"],
     "responsible_role": "CADASTRO", "is_required": True, "display_order": 4},
    {"field_name": "peso_bruto", "field_label": "Peso Bruto (kg)", "sap_field": "BRGEW",
     "sap_view": "dados_basicos", "field_type": "number", "options": None, "responsible_role": "CADASTRO",
     "is_required": False, "display_order": 5},
    {"field_name": "peso_liquido", "field_label": "Peso Líquido (kg)", "sap_field": "NTGEW",
     "sap_view": "dados_basicos", "field_type": "number", "options": None, "responsible_role": "CADASTRO",
     "is_required": False, "display_order": 6},
    {"field_name": "ncm", "field_label": "NCM", "sap_field": "J_1BNCM", "sap_view": "fiscal",
     "field_type": "text", "options": None, "responsible_role": "FISCAL", "is_required": True, "display_order": 1},
    {"field_name": "cfop", "field_label": "CFOP", "sap_field": None, "sap_view": "fiscal",
     "field_type": "select",
     "options": ["5101 - Venda de mercadoria", "5102 - Venda de mercadoria", "6101 - Compra para industrialização", "6102 - Compra para revenda"],
     "responsible_role": "FISCAL", "is_required": True, "display_order": 2},
    {"field_name": "origem_material", "field_label": "Origem do Material", "sap_field": "J_1BORIGM",
     "sap_view": "fiscal", "field_type": "select",
     "options": ["0 - Nacional", "1 - Importado Direto", "2 - Importado Adquirido no Mercado Interno"],
     "responsible_role": "FISCAL", "is_required": True, "display_order": 3},
    {"field_name": "cst_ipi", "field_label": "CST IPI", "sap_field": None, "sap_view": "fiscal",
     "field_type": "select", "options": ["00 - Entrada com crédito", "49 - Outras entradas", "50 - Saída tributada"],
     "responsible_role": "FISCAL", "is_required": False, "display_order": 4},
    {"field_name": "cst_pis_cofins", "field_label": "CST PIS/COFINS", "sap_field": None, "sap_view": "fiscal",
     "field_type": "select", "options": ["01 - Operação Tributável", "02 - Operação Tributável", "49 - Outras Operações de Saída"],
     "responsible_role": "FISCAL", "is_required": False, "display_order": 5},
    {"field_name": "grupo_compras", "field_label": "Grupo de Compras", "sap_field": "EKGRP",
     "sap_view": "compras", "field_type": "select",
     "options": ["001 - Compras Nacionais", "002 - Importação", "003 - Serviços"],
     "responsible_role": "MRP", "is_required": True, "display_order": 1},
    {"field_name": "prazo_entrega", "field_label": "Prazo de Entrega (dias)", "sap_field": "PLIFZ",
     "sap_view": "compras", "field_type": "number", "options": None, "responsible_role": "MRP",
     "is_required": False, "display_order": 2},
    {"field_name": "unidade_medida_pedido", "field_label": "Unidade de Medida Pedido", "sap_field": "BSTME",
     "sap_view": "compras", "field_type": "select",
     "options": ["UN", "KG", "L", "M", "CX", "PC"],
     "responsible_role": "MRP", "is_required": False, "display_order": 3},
    {"field_name": "tolerancia_entrega", "field_label": "Tolerância de Entrega (%)", "sap_field": "MTVFP",
     "sap_view": "compras", "field_type": "number", "options": None, "responsible_role": "MRP",
     "is_required": False, "display_order": 4},
    {"field_name": "fornecedor_preferencial", "field_label": "Fornecedor Preferencial", "sap_field": None,
     "sap_view": "compras", "field_type": "text", "options": None, "responsible_role": "MRP",
     "is_required": False, "display_order": 5},
    {"field_name": "tipo_mrp", "field_label": "Tipo MRP", "sap_field": "DISMM",
     "sap_view": "mrp", "field_type": "select",
     "options": ["PD - MRP", "VB - Consumo direto", "ND - Sem planejamento"],
     "responsible_role": "MRP", "is_required": True, "display_order": 1},
    {"field_name": "responsavel_mrp", "field_label": "Responsável MRP", "sap_field": "DISPO",
     "sap_view": "mrp", "field_type": "text", "options": None, "responsible_role": "MRP",
     "is_required": False, "display_order": 2},
    {"field_name": "estoque_minimo", "field_label": "Estoque Mínimo", "sap_field": "MINBE",
     "sap_view": "mrp", "field_type": "number", "options": None, "responsible_role": "MRP",
     "is_required": False, "display_order": 3},
    {"field_name": "tamanho_lote", "field_label": "Tamanho do Lote", "sap_field": "BSTFE",
     "sap_view": "mrp", "field_type": "number", "options": None, "responsible_role": "MRP",
     "is_required": False, "display_order": 4},
    {"field_name": "estoque_maximo", "field_label": "Estoque Máximo", "sap_field": "MABST",
     "sap_view": "mrp", "field_type": "number", "options": None, "responsible_role": "MRP",
     "is_required": False, "display_order": 5},
    {"field_name": "perfil_previsao", "field_label": "Perfil de Previsão", "sap_field": "PVRSM",
     "sap_view": "mrp", "field_type": "select",
     "options": ["A - Média móvel", "B - Consumo constante", "V - Média com tendência"],
     "responsible_role": "MRP", "is_required": False, "display_order": 6},
    {"field_name": "conta_estoque", "field_label": "Conta de Estoque", "sap_field": None,
     "sap_view": "contabilidade", "field_type": "text", "options": None, "responsible_role": "CONTABILIDADE",
     "is_required": True, "display_order": 1},
    {"field_name": "centro_lucro", "field_label": "Centro de Lucro", "sap_field": "PRCTR",
     "sap_view": "contabilidade", "field_type": "text", "options": None, "responsible_role": "CONTABILIDADE",
     "is_required": False, "display_order": 2},
    {"field_name": "grupo_valoracao", "field_label": "Grupo de Valoração", "sap_field": "BKLAS",
     "sap_view": "contabilidade", "field_type": "select",
     "options": ["3000 - Matéria-prima", "7900 - Produto acabado", "7920 - Mercadoria para revenda"],
     "responsible_role": "CONTABILIDADE", "is_required": True, "display_order": 3},
    {"field_name": "controle_preco", "field_label": "Controle de Preço", "sap_field": "VPRSV",
     "sap_view": "contabilidade", "field_type": "select",
     "options": ["S - Preço padrão", "V - Custo médio móvel", "D - Preço de mercado"],
     "responsible_role": "CONTABILIDADE", "is_required": True, "display_order": 4},
    {"field_name": "preco_padrao", "field_label": "Preço Padrão", "sap_field": "STPRS",
     "sap_view": "contabilidade", "field_type": "number", "options": None, "responsible_role": "CONTABILIDADE",
     "is_required": False, "display_order": 5},
    {"field_name": "org_vendas", "field_label": "Organização de Vendas", "sap_field": "VKORG",
     "sap_view": "vendas", "field_type": "select",
     "options": ["1000 - Organização 1000", "2000 - Organização 2000"],
     "responsible_role": "CONTABILIDADE", "is_required": False, "display_order": 1},
    {"field_name": "canal_distribuicao", "field_label": "Canal de Distribuição", "sap_field": "VTWEG",
     "sap_view": "vendas", "field_type": "select",
     "options": ["10 - Varejo", "20 - Atacado", "30 - Exportação"],
     "responsible_role": "CONTABILIDADE", "is_required": False, "display_order": 2},
    {"field_name": "grupo_material", "field_label": "Grupo de Material", "sap_field": "WGBEZ",
     "sap_view": "vendas", "field_type": "select",
     "options": ["01 - Produtos acabados", "02 - Materiais de embalagem"],
     "responsible_role": "CONTABILIDADE", "is_required": False, "display_order": 3},
    {"field_name": "unidade_venda", "field_label": "Unidade de Venda", "sap_field": "VRKME",
     "sap_view": "vendas", "field_type": "select",
     "options": ["UN", "KG", "CX", "PC"],
     "responsible_role": "CONTABILIDADE", "is_required": False, "display_order": 4},
]
